sonar.projectKey=DonatoCorbacioDev_bcm-v2-frontend
sonar.organization=donatocorbaciodev

sonar.sources=.
sonar.exclusions=node_modules/**,**/__tests__/**,.next/**,coverage/**,**/*.d.ts,public/**

sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=app/**,jest.setup.ts,jest.env.ts,jest.config.js,eslint.config.mjs,next.config.ts,tailwind.config.ts,postcss.config.mjs,providers/**
